// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaOrdenesReparacion.DA;

#nullable disable

namespace SistemaOrdenesReparacion.DA.Migrations
{
    [DbContext(typeof(TallerDbContext))]
    partial class TallerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.InventarioDeRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("money")
                        .HasColumnName("PrecioUnitario");

                    b.HasKey("Id");

                    b.ToTable("InventarioDeRepuestos");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.InventarioDeServicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("money")
                        .HasColumnName("Precio");

                    b.HasKey("Id");

                    b.ToTable("InventarioDeServicios");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.Mecanico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Identificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenDeTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AñoDeFabricacion")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionDelProblema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAproximadaDeFinalizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Mecanico")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotivoDeCancelacion")
                        .HasColumnType("text");

                    b.Property<int>("TipoDeCombustionInterna")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDeVehiculo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("Id_Mecanico");

                    b.ToTable("OrdenesDeTrabajos");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_InventarioDeRepuestos")
                        .HasColumnType("integer");

                    b.Property<int>("Id_OrdenesDeTrabajos")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_InventarioDeRepuestos");

                    b.HasIndex("Id_OrdenesDeTrabajos");

                    b.ToTable("OrdenesDeTrabajoInventarioDeRepuestos");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_InventarioDeServicios")
                        .HasColumnType("integer");

                    b.Property<int>("Id_OrdenesDeTrabajo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_InventarioDeServicios");

                    b.HasIndex("Id_OrdenesDeTrabajo");

                    b.ToTable("OrdenesDeTrabajoInventarioDeServicios");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaUltimoCambioClave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Cliente")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Mecanico")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cliente")
                        .IsUnique();

                    b.HasIndex("Id_Mecanico")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenDeTrabajo", b =>
                {
                    b.HasOne("SistemaOrdenesReparacion.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOrdenesReparacion.Model.Mecanico", "Mecanico")
                        .WithMany("OrdenesAsignadas")
                        .HasForeignKey("Id_Mecanico");

                    b.Navigation("Cliente");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenRepuesto", b =>
                {
                    b.HasOne("SistemaOrdenesReparacion.Model.InventarioDeRepuesto", "Repuesto")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_InventarioDeRepuestos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOrdenesReparacion.Model.OrdenDeTrabajo", "OrdenDeTrabajo")
                        .WithMany("Repuestos")
                        .HasForeignKey("Id_OrdenesDeTrabajos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenDeTrabajo");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenServicio", b =>
                {
                    b.HasOne("SistemaOrdenesReparacion.Model.InventarioDeServicios", "Servicio")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_InventarioDeServicios")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOrdenesReparacion.Model.OrdenDeTrabajo", "OrdenDeTrabajo")
                        .WithMany("Servicios")
                        .HasForeignKey("Id_OrdenesDeTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenDeTrabajo");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.Usuario", b =>
                {
                    b.HasOne("SistemaOrdenesReparacion.Model.Cliente", "Cliente")
                        .WithOne("Usuario")
                        .HasForeignKey("SistemaOrdenesReparacion.Model.Usuario", "Id_Cliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaOrdenesReparacion.Model.Mecanico", "Mecanico")
                        .WithOne("Usuario")
                        .HasForeignKey("SistemaOrdenesReparacion.Model.Usuario", "Id_Mecanico")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.Cliente", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.InventarioDeRepuesto", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.InventarioDeServicios", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.Mecanico", b =>
                {
                    b.Navigation("OrdenesAsignadas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaOrdenesReparacion.Model.OrdenDeTrabajo", b =>
                {
                    b.Navigation("Repuestos");

                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
